- name: Transfer the script to remote node
  template:
    src: 'templates/shell/{{ item.src }}'
    dest: '/var/tmp/{{ item.dest }}'
    owner: root
    group: root
    mode: 755
    #backup: yes
  with_items:
    - { src: 'commands.j2', dest: 'commands.sh' }
    - { src: 'nologin-account.j2', dest: 'nologin-account.sh' }

- name: Execute the script for RHEL9 environment specific changes 
  command: sh /var/tmp/commands.sh

- name: 5.4.2 Ensure system accounts are non-login
  command: sh /var/tmp/nologin-account.sh

- name: Delete content & directory
  ansible.builtin.file:
    state: absent
    path: /var/tmp/commands.sh

- name: Delete content & directory2
  ansible.builtin.file:
    state: absent
    path: /var/tmp/nologin-account.sh


###################################################################################

- name: Create /etc/hosts.allow and /etc/hosts.deny SEC - 3.15
  shell: touch /etc/hosts.allow /etc/hosts.deny
- name: Ensure permissions on /etc/hosts.allow are configured  SEC- 3.15 
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - { path: '/etc/hosts.allow', state: 'file', mode: '0644', owner: 'root', group: 'root' }
    - { path: '/etc/hosts.deny', state: 'file', mode: '0644', owner: 'root', group: 'root' }

####################################################################################
- name: Check if listed package are installed - SEC 3.17 
  command: rpm -qa "{{ item }}"
  loop:
    - iptables-libs
  register: package_check
  when: ansible_facts['os_family'] == "RedHat"
- name: Print package installation  results
  debug:
    msg: "Iptables package is installed already"
  when: package_check is succeeded

- name: Install Iptables package since rpm not installed already
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - iptables
  when: package_check is failed

