# the Ansible role dependency mechanism.
os_hardening_enabled: true

#####with in tasks#####################
all_tasks_execute: true

#######################################################
# Remove packages with known security issues used by - 2.2
os_security_packages_clean: true
os_security_packages_list: ['xinetd', 'inetd', 'ypserv', 'telnet-server', 'rsh-server', 'prelink']

#######################################################
# Set the SELinux state, which can be either disabled permissive or enforcing - 2.7
os_selinux_state: enforcing
# Set the SELinux polixy.
os_selinux_policy: targeted

# Mount options for proc in /etc/fstab.
#proc_mnt_options: 'rw,nosuid,nodev,noexec,relatime,hidepid={{ hidepid_option }}'
proc_mnt_options: 'default,nosuid,nodev,noexec,hidepid={{ hidepid_option }}'

############may 10#######################
# 5.2.5
cis_sshd_max_auth_tries: 4

# 5.2.11
cis_sshd_ciphers: "aes256-ctr,aes192-ctr,aes128-ctr"

# 5.2.12
cis_sshd_macs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"

# 5.2.13
cis_sshd_client_alive_interval: 300
cis_sshd_client_alive_count_max: 0

# 5.2.14
cis_sshd_login_grace_time: 60

# 5.2.15
cis_sshd_allow_users: "" # A comma-delimited list of users to allow ssh access to
cis_sshd_allow_groups: "" # A comma-delimited list of groups ot allow ssh access to
cis_sshd_deny_users: "" # A comma-delimited list of users to deny ssh access for
cis_sshd_deny_groups: "" # A comma-delimited list of groups to deny ssh access for

# 5.2.16
cis_sshd_banner: "/etc/issue.net"

# 5.3.1
cis_pwquality_minlen: "14" # Minimum number of characters required for passwords
cis_pwquality_dcredit: "-1" # At least one digit must be provided
cis_pwquality_ucredit: "-1" # At least one uppercase character must be provided
cis_pwquality_ocredit: "-1" # At least one special character must be provided
cis_pwquality_lcredit: "-1" # At least one lowercase character must be provided
cis_pwquality_remember: "10" # At least one lowercase character must be provided


# 5.3.2
cis_pwfailed_attempts: "5" # Number of failed login attempts before account locked
cis_pwunlock_time: "900" # Time in seconds before the login attempt can be tried again without auto failing

# 5.3.3
cis_pwretry_number: "3" # Number of times a password can be attempted before sending back a failure
cis_pwreuse_number: "10" # Ensure password reuse is limited to this number

# 5.3.4
cis_passwd_hash: "sha512" # Options are sha512 or md5